name: Python Run

on:
  schedule:
    # 分 時 日 月 曜日
    # */X でX間隔
    - cron: '00 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      chromedriver: chromedriver
      line_post_url: ${{secrets.NOTIFY_URL}}
      access_token: ${{secrets.ACCESS_TOKEN}}
    strategy:
      matrix:
        python-version: [3.9]


    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        curl -OL "https://chromedriver.storage.googleapis.com/95.0.4638.69/chromedriver_linux64.zip"
        unzip -n chromedriver_linux64.zip
    - name: scrayping and notify
      run: |
        python main.py
    - name: Commit files
      run: |
        ls
        if ! git diff --exit-code --quiet
        then
          git config user.email "hayakap1211@gmail.com"
          git config user.name "HayatoKTYM"
          git add -u
          git commit -m "Add changes by Actions"
          git push origin main
        fi
